"""Static seed catalogue.

Brands and product names are invented so the repository carries no real
trademarks, but prices, rating spreads and stock levels are chosen to look like
a real shop: a handful of items are deliberately out of stock or nearly so,
which gives the inventory and checkout suites realistic edge cases to hit
without having to manufacture them first.

Data is plain tuples rather than ORM objects so this module stays importable
with no database, and the counts can be asserted in a unit test.
"""

from __future__ import annotations

from dataclasses import dataclass
from decimal import Decimal


@dataclass(frozen=True, slots=True)
class SeedCategory:
    name: str
    slug: str
    description: str


@dataclass(frozen=True, slots=True)
class SeedProduct:
    sku: str
    name: str
    brand: str
    category_slug: str
    price: Decimal
    rating: Decimal
    stock: int
    description: str
    is_active: bool = True


CATEGORIES: tuple[SeedCategory, ...] = (
    SeedCategory("Laptops", "laptops", "Ultrabooks, creator machines and portable workstations."),
    SeedCategory("Phones", "phones", "Smartphones across the budget and flagship range."),
    SeedCategory("Electronics", "electronics", "Audio, wearables, cameras and smart home devices."),
    SeedCategory("Accessories", "accessories", "Cables, chargers, bags, docks and input devices."),
    SeedCategory("Home", "home", "Kitchen, lighting and small appliances."),
    SeedCategory("Clothing", "clothing", "Everyday apparel and outerwear."),
    SeedCategory("Books", "books", "Technical and general-interest titles."),
)


def _d(value: str) -> Decimal:
    return Decimal(value)


PRODUCTS: tuple[SeedProduct, ...] = (
    # ---------------------------------------------------------------- Laptops
    SeedProduct(
        "LAP-1001",
        "Aurora 14 Ultrabook",
        "Aurora",
        "laptops",
        _d("1249.00"),
        _d("4.6"),
        24,
        "A 14-inch magnesium-alloy ultrabook weighing 1.1 kg, with a 2.8K OLED display and 18-hour battery life.",
    ),
    SeedProduct(
        "LAP-1002",
        "Aurora 16 Creator Pro",
        "Aurora",
        "laptops",
        _d("2199.00"),
        _d("4.8"),
        11,
        "16-inch colour-calibrated laptop with a discrete GPU and a 140 W charger, built for video editing.",
    ),
    SeedProduct(
        "LAP-1003",
        "Kestrel Studio 15",
        "Kestrel",
        "laptops",
        _d("1599.50"),
        _d("4.4"),
        17,
        "Aluminium 15-inch workstation with 32 GB of memory and a user-replaceable SSD.",
    ),
    SeedProduct(
        "LAP-1004",
        "Kestrel Air 13",
        "Kestrel",
        "laptops",
        _d("899.99"),
        _d("4.2"),
        40,
        "Fanless 13-inch laptop for students and travel, with a matte 16:10 screen.",
    ),
    SeedProduct(
        "LAP-1005",
        "Nimbus Flex 2-in-1",
        "Nimbus",
        "laptops",
        _d("1049.00"),
        _d("4.1"),
        15,
        "Convertible touchscreen laptop with a 360-degree hinge and bundled stylus.",
    ),
    SeedProduct(
        "LAP-1006",
        "Nimbus Workhorse 17",
        "Nimbus",
        "laptops",
        _d("1899.00"),
        _d("4.3"),
        6,
        "17-inch desktop replacement with a numeric keypad and four-zone cooling.",
    ),
    SeedProduct(
        "LAP-1007",
        "Aurora Edu 11",
        "Aurora",
        "laptops",
        _d("429.00"),
        _d("3.8"),
        62,
        "Rugged 11-inch laptop for classrooms, drop-tested to 70 cm with a spill-resistant keyboard.",
    ),
    SeedProduct(
        "LAP-1008",
        "Kestrel Titan Gaming 15",
        "Kestrel",
        "laptops",
        _d("1749.00"),
        _d("4.5"),
        0,
        "165 Hz gaming laptop with vapour-chamber cooling and per-key RGB lighting.",
    ),
    # ----------------------------------------------------------------- Phones
    SeedProduct(
        "PHN-2001",
        "Vertex 12 Pro",
        "Vertex",
        "phones",
        _d("1099.00"),
        _d("4.7"),
        33,
        "6.7-inch flagship with a triple camera system, titanium frame and 45 W fast charging.",
    ),
    SeedProduct(
        "PHN-2002",
        "Vertex 12",
        "Vertex",
        "phones",
        _d("849.00"),
        _d("4.5"),
        48,
        "The standard flagship: 6.1-inch OLED, dual cameras and all-day battery.",
    ),
    SeedProduct(
        "PHN-2003",
        "Vertex 12 Mini",
        "Vertex",
        "phones",
        _d("699.00"),
        _d("4.0"),
        21,
        "A 5.4-inch phone for people who still want to reach the whole screen one-handed.",
    ),
    SeedProduct(
        "PHN-2004",
        "Lumen A7",
        "Lumen",
        "phones",
        _d("329.00"),
        _d("4.1"),
        75,
        "Mid-range phone with a 5000 mAh battery, headphone jack and expandable storage.",
    ),
    SeedProduct(
        "PHN-2005",
        "Lumen A5 Lite",
        "Lumen",
        "phones",
        _d("199.99"),
        _d("3.7"),
        90,
        "Budget handset with a 90 Hz display and a two-day battery.",
    ),
    SeedProduct(
        "PHN-2006",
        "Kestrel Field Phone",
        "Kestrel",
        "phones",
        _d("549.00"),
        _d("4.3"),
        14,
        "IP68 rugged phone with a programmable side key and glove-friendly touchscreen.",
    ),
    SeedProduct(
        "PHN-2007",
        "Lumen Fold X",
        "Lumen",
        "phones",
        _d("1499.00"),
        _d("3.9"),
        4,
        "Book-style folding phone with a 7.6-inch inner display and a crease-reduced hinge.",
    ),
    # ------------------------------------------------------------ Electronics
    SeedProduct(
        "ELE-3001",
        "Nimbus Noise-Cancelling Headphones",
        "Nimbus",
        "electronics",
        _d("249.99"),
        _d("4.6"),
        55,
        "Over-ear wireless headphones with adaptive noise cancelling and 40-hour battery life.",
    ),
    SeedProduct(
        "ELE-3002",
        "Nimbus Buds Pro",
        "Nimbus",
        "electronics",
        _d("149.00"),
        _d("4.4"),
        120,
        "Wireless earbuds with in-ear detection, a wireless charging case and IPX4 sweat resistance.",
    ),
    SeedProduct(
        "ELE-3003",
        "Sonaris Studio Monitor Pair",
        "Sonaris",
        "electronics",
        _d("399.00"),
        _d("4.7"),
        12,
        "Two-way active studio monitors with a 5-inch woofer and balanced XLR inputs.",
    ),
    SeedProduct(
        "ELE-3004",
        "Sonaris Portable Speaker",
        "Sonaris",
        "electronics",
        _d("129.00"),
        _d("4.2"),
        68,
        "IP67 waterproof Bluetooth speaker with 24 hours of playback and a carry strap.",
    ),
    SeedProduct(
        "ELE-3005",
        "Vertex Watch Series 5",
        "Vertex",
        "electronics",
        _d("399.00"),
        _d("4.5"),
        37,
        "Smartwatch with ECG, blood-oxygen sensing and a sapphire crystal face.",
    ),
    SeedProduct(
        "ELE-3006",
        "Vertex Watch SE",
        "Vertex",
        "electronics",
        _d("249.00"),
        _d("4.3"),
        44,
        "The essentials: heart rate, sleep tracking, notifications and a five-day battery.",
    ),
    SeedProduct(
        "ELE-3007",
        "Corvid 4K Action Camera",
        "Corvid",
        "electronics",
        _d("329.00"),
        _d("4.4"),
        26,
        "Waterproof 4K/120 action camera with horizon levelling and dual displays.",
    ),
    SeedProduct(
        "ELE-3008",
        "Corvid Mirrorless M200",
        "Corvid",
        "electronics",
        _d("1299.00"),
        _d("4.8"),
        8,
        "24 MP APS-C mirrorless camera body with in-body stabilisation and a tilting screen.",
    ),
    SeedProduct(
        "ELE-3009",
        "Nimbus Smart Doorbell",
        "Nimbus",
        "electronics",
        _d("179.00"),
        _d("3.9"),
        41,
        "1080p doorbell camera with two-way audio and local recording to a microSD card.",
    ),
    SeedProduct(
        "ELE-3010",
        "Nimbus Mesh Wi-Fi 6 (3-pack)",
        "Nimbus",
        "electronics",
        _d("299.00"),
        _d("4.5"),
        19,
        "Tri-band mesh Wi-Fi covering up to 500 square metres, with wired backhaul support.",
    ),
    SeedProduct(
        "ELE-3011",
        "Sonaris Turntable Classic",
        "Sonaris",
        "electronics",
        _d("449.00"),
        _d("4.6"),
        7,
        "Belt-driven turntable with an aluminium tonearm and a built-in phono preamp.",
    ),
    SeedProduct(
        "ELE-3012",
        "Corvid Drone Scout",
        "Corvid",
        "electronics",
        _d("799.00"),
        _d("4.1"),
        0,
        "Sub-250 g folding drone with 4K video, 34 minutes of flight time and obstacle sensing.",
    ),
    # ------------------------------------------------------------ Accessories
    SeedProduct(
        "ACC-4001",
        "Nimbus 100W USB-C Charger",
        "Nimbus",
        "accessories",
        _d("59.99"),
        _d("4.5"),
        200,
        "Compact GaN charger with two USB-C ports and one USB-A, enough for a laptop and a phone.",
    ),
    SeedProduct(
        "ACC-4002",
        "Nimbus USB-C Cable 2m",
        "Nimbus",
        "accessories",
        _d("19.99"),
        _d("4.3"),
        350,
        "Braided 240 W USB-C cable rated for 20 Gbps data and 10,000 bend cycles.",
    ),
    SeedProduct(
        "ACC-4003",
        "Corvid Laptop Backpack 20L",
        "Corvid",
        "accessories",
        _d("119.00"),
        _d("4.6"),
        47,
        "Water-resistant 20-litre backpack with a suspended 16-inch laptop compartment.",
    ),
    SeedProduct(
        "ACC-4004",
        "Corvid Camera Sling",
        "Corvid",
        "accessories",
        _d("89.00"),
        _d("4.4"),
        31,
        "Cross-body camera bag with a quick-access side entry and removable dividers.",
    ),
    SeedProduct(
        "ACC-4005",
        "Nimbus Thunderbolt Dock",
        "Nimbus",
        "accessories",
        _d("279.00"),
        _d("4.2"),
        16,
        "Single-cable dock driving two 4K displays, gigabit ethernet and 90 W laptop charging.",
    ),
    SeedProduct(
        "ACC-4006",
        "Sonaris Mechanical Keyboard 75",
        "Sonaris",
        "accessories",
        _d("159.00"),
        _d("4.7"),
        29,
        "Hot-swappable 75% mechanical keyboard with a gasket mount and PBT keycaps.",
    ),
    SeedProduct(
        "ACC-4007",
        "Sonaris Vertical Mouse",
        "Sonaris",
        "accessories",
        _d("69.00"),
        _d("4.1"),
        58,
        "Ergonomic vertical mouse with a 4000 DPI sensor and six programmable buttons.",
    ),
    SeedProduct(
        "ACC-4008",
        "Nimbus Monitor Arm",
        "Nimbus",
        "accessories",
        _d("109.00"),
        _d("4.5"),
        34,
        "Gas-spring monitor arm supporting displays up to 32 inches and 9 kg.",
    ),
    SeedProduct(
        "ACC-4009",
        "Corvid Tripod Carbon",
        "Corvid",
        "accessories",
        _d("229.00"),
        _d("4.6"),
        13,
        "Carbon-fibre travel tripod folding to 42 cm, with a ball head and 12 kg load rating.",
    ),
    SeedProduct(
        "ACC-4010",
        "Nimbus Power Bank 20000",
        "Nimbus",
        "accessories",
        _d("79.99"),
        _d("4.4"),
        88,
        "20,000 mAh power bank with 65 W USB-C output and a pass-through charging mode.",
    ),
    SeedProduct(
        "ACC-4011",
        "Nimbus Screen Cleaning Kit",
        "Nimbus",
        "accessories",
        _d("14.99"),
        _d("3.6"),
        240,
        "Alcohol-free spray with two microfibre cloths, safe for coated laptop displays.",
    ),
    SeedProduct(
        "ACC-4012",
        "Sonaris Desk Mat XL",
        "Sonaris",
        "accessories",
        _d("39.00"),
        _d("4.2"),
        96,
        "900 x 400 mm stitched-edge desk mat with a low-friction surface.",
    ),
    # ------------------------------------------------------------------- Home
    SeedProduct(
        "HOM-5001",
        "Hearthwell Espresso Machine",
        "Hearthwell",
        "home",
        _d("649.00"),
        _d("4.5"),
        9,
        "Dual-boiler espresso machine with PID temperature control and a 58 mm portafilter.",
    ),
    SeedProduct(
        "HOM-5002",
        "Hearthwell Burr Grinder",
        "Hearthwell",
        "home",
        _d("199.00"),
        _d("4.4"),
        27,
        "Conical burr grinder with 40 grind settings, stepless enough for espresso.",
    ),
    SeedProduct(
        "HOM-5003",
        "Hearthwell Air Fryer 5L",
        "Hearthwell",
        "home",
        _d("129.00"),
        _d("4.3"),
        52,
        "5-litre air fryer with a dishwasher-safe basket and eight presets.",
    ),
    SeedProduct(
        "HOM-5004",
        "Hearthwell Stand Mixer",
        "Hearthwell",
        "home",
        _d("379.00"),
        _d("4.7"),
        14,
        "1000 W tilt-head stand mixer with a 4.8-litre bowl and planetary mixing action.",
    ),
    SeedProduct(
        "HOM-5005",
        "Verdant Desk Lamp",
        "Verdant",
        "home",
        _d("89.00"),
        _d("4.2"),
        71,
        "Adjustable LED desk lamp with a flicker-free driver and five colour temperatures.",
    ),
    SeedProduct(
        "HOM-5006",
        "Verdant Air Purifier",
        "Verdant",
        "home",
        _d("249.00"),
        _d("4.4"),
        22,
        "HEPA-13 purifier rated for 40 square metres, with a night mode under 24 dB.",
    ),
    SeedProduct(
        "HOM-5007",
        "Verdant Cordless Vacuum",
        "Verdant",
        "home",
        _d("399.00"),
        _d("4.1"),
        18,
        "Cordless stick vacuum with 60 minutes of runtime and a self-standing charging dock.",
    ),
    SeedProduct(
        "HOM-5008",
        "Hearthwell Cast Iron Skillet 12in",
        "Hearthwell",
        "home",
        _d("59.00"),
        _d("4.8"),
        64,
        "Pre-seasoned 12-inch cast iron skillet with a helper handle. Oven safe to 260 C.",
    ),
    SeedProduct(
        "HOM-5009",
        "Verdant Weighted Blanket 7kg",
        "Verdant",
        "home",
        _d("99.00"),
        _d("4.0"),
        38,
        "Seven-kilogram weighted blanket with glass beads and a washable cotton cover.",
    ),
    # --------------------------------------------------------------- Clothing
    SeedProduct(
        "CLO-6001",
        "Northgate Rain Shell",
        "Northgate",
        "clothing",
        _d("189.00"),
        _d("4.5"),
        43,
        "Three-layer waterproof shell with taped seams and pit zips. Packs into its own pocket.",
    ),
    SeedProduct(
        "CLO-6002",
        "Northgate Down Jacket",
        "Northgate",
        "clothing",
        _d("249.00"),
        _d("4.6"),
        25,
        "700-fill responsibly sourced down jacket with a water-repellent finish.",
    ),
    SeedProduct(
        "CLO-6003",
        "Northgate Merino Base Layer",
        "Northgate",
        "clothing",
        _d("79.00"),
        _d("4.4"),
        110,
        "180 gsm merino wool long-sleeve base layer with flatlock seams.",
    ),
    SeedProduct(
        "CLO-6004",
        "Verdant Organic Tee",
        "Verdant",
        "clothing",
        _d("29.00"),
        _d("4.1"),
        260,
        "Organic cotton t-shirt in a relaxed fit, pre-shrunk and GOTS certified.",
    ),
    SeedProduct(
        "CLO-6005",
        "Verdant Chino Trousers",
        "Verdant",
        "clothing",
        _d("69.00"),
        _d("4.0"),
        87,
        "Stretch cotton chinos with a hidden zip pocket and a tapered leg.",
    ),
    SeedProduct(
        "CLO-6006",
        "Northgate Trail Runners",
        "Northgate",
        "clothing",
        _d("139.00"),
        _d("4.3"),
        36,
        "Trail running shoes with a 6 mm drop, rock plate and 4 mm lugs.",
    ),
    SeedProduct(
        "CLO-6007",
        "Verdant Wool Beanie",
        "Verdant",
        "clothing",
        _d("24.00"),
        _d("3.9"),
        175,
        "Ribbed merino beanie with a fold-over cuff. One size.",
    ),
    # ------------------------------------------------------------------ Books
    SeedProduct(
        "BOK-7001",
        "Designing Data-Heavy Systems",
        "Quillstone Press",
        "books",
        _d("54.99"),
        _d("4.8"),
        46,
        "A practical tour of storage engines, replication and consistency trade-offs.",
    ),
    SeedProduct(
        "BOK-7002",
        "The Pragmatic Tester",
        "Quillstone Press",
        "books",
        _d("42.00"),
        _d("4.6"),
        58,
        "How to choose the right testing layer, and how to keep a suite from rotting.",
    ),
    SeedProduct(
        "BOK-7003",
        "Python for Working Engineers",
        "Quillstone Press",
        "books",
        _d("39.99"),
        _d("4.4"),
        92,
        "Typing, packaging, async and profiling, aimed at people who already ship Python.",
    ),
    SeedProduct(
        "BOK-7004",
        "Continuous Delivery in Practice",
        "Beacon House",
        "books",
        _d("47.50"),
        _d("4.5"),
        33,
        "Pipeline design, deployment strategies and what to do when the build goes red.",
    ),
    SeedProduct(
        "BOK-7005",
        "The Quiet Observatory",
        "Beacon House",
        "books",
        _d("18.99"),
        _d("4.2"),
        140,
        "A novel about an astronomer, a decommissioned telescope and a very long winter.",
    ),
    SeedProduct(
        "BOK-7006",
        "Salt, Smoke and Time",
        "Beacon House",
        "books",
        _d("32.00"),
        _d("4.7"),
        61,
        "A cookbook on curing, fermenting and preserving, with 90 tested recipes.",
    ),
    SeedProduct(
        "BOK-7007",
        "Legacy Systems Field Guide",
        "Quillstone Press",
        "books",
        _d("44.00"),
        _d("3.8"),
        0,
        "Strategies for changing software you did not write and cannot fully test.",
    ),
    SeedProduct(
        "BOK-7008",
        "Discontinued Style Manual",
        "Beacon House",
        "books",
        _d("21.00"),
        _d("3.2"),
        5,
        "An out-of-print writing guide, kept in the catalogue as an inactive product.",
        is_active=False,
    ),
)

PROMOTIONS: tuple[dict[str, object], ...] = (
    {
        "code": "WELCOME10",
        "description": "10% off your first order",
        "discount_type": "percentage",
        "value": Decimal("10"),
        "min_subtotal": Decimal("0"),
        "max_discount": Decimal("100.00"),
    },
    {
        "code": "SAVE15",
        "description": "$15 off orders over $150",
        "discount_type": "fixed",
        "value": Decimal("15.00"),
        "min_subtotal": Decimal("150.00"),
        "max_discount": None,
    },
    {
        "code": "BIGSPENDER",
        "description": "20% off orders over $1000, capped at $150",
        "discount_type": "percentage",
        "value": Decimal("20"),
        "min_subtotal": Decimal("1000.00"),
        "max_discount": Decimal("150.00"),
    },
    {
        # Present so the "expired code" path has something real to exercise;
        # the seeder backdates valid_to.
        "code": "EXPIRED20",
        "description": "20% off - expired promotion, kept for testing",
        "discount_type": "percentage",
        "value": Decimal("20"),
        "min_subtotal": Decimal("0"),
        "max_discount": None,
        "expired": True,
    },
    {
        "code": "INACTIVE5",
        "description": "$5 off - deactivated promotion, kept for testing",
        "discount_type": "fixed",
        "value": Decimal("5.00"),
        "min_subtotal": Decimal("0"),
        "max_discount": None,
        "inactive": True,
    },
)

# Demo customer accounts. Passwords come from configuration, never from here.
CUSTOMERS: tuple[tuple[str, str], ...] = (
    ("alice@shopsphere.test", "Alice Nakamura"),
    ("ben@shopsphere.test", "Ben Okonkwo"),
    ("carla@shopsphere.test", "Carla Mendes"),
    ("dev@shopsphere.test", "Dev Sharma"),
)


def image_url_for(sku: str) -> str:
    """Deterministic placeholder image URL.

    Seeded by SKU so a product always renders the same picture, which keeps
    visual comparisons and screenshots stable. The frontend falls back to a
    generated tile when the image cannot be fetched, so the UI still works with
    no internet access.
    """
    return f"https://picsum.photos/seed/{sku.lower()}/600/600"
